### ISSUE TITLE
Magento install fails during compile

### ISSUE THREAD

**Issue by jorgb90** [magenx/Magento-2-server-installation#77]
Just tried to install a new server, but with the recent updates to PHP 8.1 and Magento 2.4.4 Magento fails to go in production mode with this installer during install:

Starting compilation
Something went wrong while compiling generated code. See the error log for details.
Disabling maintenance mode
Command returned non-zero exit code:
`/usr/bin/php8.1 -f /home/xxxxx/public_html/bin/magento setup:di:compile`

[2022-04-15T13:23:41.787997+00:00] main.ERROR: /usr/bin/php8.1 -f /home/xxxxx/public_html/bin/magento setup:di:compile 2>&1
Compilation was started.
%message% 0/9 [>---------------------------]   0% < 1 sec 58.0 MiBProxies code generation... 0/9 [>---------------------------]   0% < 1 sec 58.0 MiB
Proxies code generation... 1/9 [===>------------------------]  11% 1 sec 60.0 MiB
Repositories code generation... 1/9 [===>------------------------]  11% 1 sec 60.0 MiBInterface "Magento\GraphQl\Helper\Error\ExceptionMessageFormatterInterface" not found#0 /home/xxxxxx/public_html/vendor/composer/ClassLoader.php(571): include()
#1 /home/xxxxxx/public_html/vendor/composer/ClassLoader.php(428): Composer\Autoload\includeFile()
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass()
#3 /home/xxxxxx/public_html/setup/src/Magento/Setup/Module/Di/Code/Reader/ClassesScanner.php(134): class_exists()
#4 /home/xxxxxx/public_html/setup/src/Magento/Setup/Module/Di/Code/Reader/ClassesScanner.php(117): Magento\Setup\Module\Di\Code\Reader\ClassesScanner->includeClass()
#5 /home/xxxxxx/public_html/setup/src/Magento/Setup/Module/Di/Code/Reader/ClassesScanner.php(87): Magento\Setup\Module\Di\Code\Reader\ClassesScanner->extract()
#6 /home/xxxxxx/public_html/setup/src/Magento/Setup/Module/Di/App/Task/Operation/RepositoryGenerator.php(61): Magento\Setup\Module\Di\Code\Reader\ClassesScanner->getList()
#7 /home/xxxxxx/public_html/setup/src/Magento/Setup/Module/Di/App/Task/Manager.php(56): Magento\Setup\Module\Di\App\Task\Operation\RepositoryGenerator->doOperation()
#8 /home/xxxxxx/public_html/setup/src/Magento/Setup/Console/Command/DiCompileCommand.php(216): Magento\Setup\Module\Di\App\Task\Manager->process()
#9 /home/xxxxxx/public_html/vendor/symfony/console/Command/Command.php(255): Magento\Setup\Console\Command\DiCompileCommand->execute()
#10 /home/xxxxxx/public_html/vendor/symfony/console/Application.php(1009): Symfony\Component\Console\Command\Command->run()
#11 /home/xxxxxx/public_html/vendor/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand()
#12 /home/xxxxxx/public_html/vendor/magento/framework/Console/Cli.php(115): Symfony\Component\Console\Application->doRun()
#13 /home/xxxxxx/public_html/vendor/symfony/console/Application.php(149): Magento\Framework\Console\Cli->doRun()
#14 /home/xxxxxx/public_html/bin/magento(23): Symfony\Component\Console\Application->run()
#15 {main}
 [] []

**Comment by jorgb90** [comment]
"magento/module-graph-ql": "*",
        "magento/module-graph-ql-cache": "*",
        "magento/module-new-relic-reporting": "*",

are required? and need to be removed from composer.json under replace section. Then compile works.

**Comment by jorgb90** [comment]
I see you added changes to overcome this issue. Perfect.
